name: flutter_util_hub
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  google_fonts: ^5.1.0
  go_router: ^10.0.0
  cached_network_image: ^3.2.3
  loading_indicator: ^3.1.1
  awesome_dialog: ^3.1.0
  progress_dialog_null_safe: ^1.0.7
  email_validator: ^2.1.17
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.12
  flutter_bloc: ^8.1.3
  url_strategy: ^0.2.0
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  get_it: ^7.6.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
